title: Laila Samsia Roathayni # your name (or website title) here
logo: "images/phcr 2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Junior Data Scientist. I am a participant of Data Science Bootcamp Batch 9 held by Shift Academy.
  I can perform EDA and machine learning. I am motivated to learn new skills and work in a team. 
  I have a good communication skills, hardworker, detail-oriented and best work under pressure
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
  <br><br>

theme: jekyll-theme-minimal
