title: <p align="center"> Laila Samsia Roathayni </p> # your name (or website title) here
logo: "images/phcr 2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/lailasamsia/">LinkedIn</a> |
  <a href="https://github.com/lailasamsia">GitHub</a>
  </p>
  <p align="justify">
  I am a Data Scientist. I have completed Data Science Bootcamp held by Shift Academy.
  I got BE degree in Geophysical Engineering at UPN Veteran Yogyakarta.
  <br><br>
  Expertise:
  Python | MySQL | Tableau | R | Ms. Excel | Oracle Data Modeler
  <br>

theme: jekyll-theme-minimal
